require("prototypes.category")
require("prototypes.entities")
require("prototypes.item-groups")
require("prototypes.items")
require("prototypes.plates-bulk-recipe")
require("prototypes.item-recipes")
require("prototypes.sounds")
require("prototypes.utility-sound")
